### ISSUE TITLE
1.0.4 + GT6.06.11, no create world

### ISSUE THREAD

**Issue by lightdo-t** [GWYOG/GTNEIOrePlugin#4]
gtneioreplugin-1.7.10-1.0.4+gregtech_1.7.10-6.06.11，no create world，单机创建不了世界。

**Comment by Tanimodori** [comment]
This issue is already existed with GT 6.05.41, due to changes made to the worldgen codes of GT. It happens when you try to enter a world. A typical FML log follows.

> [Server thread/ERROR] [FML/]: Caught exception from gtneioreplugin
> java.lang.NoClassDefFoundError: gregapi/worldgen/Worldgen_GT_Ore_Layer
> 	at pers.gwyog.gtneioreplugin.util.GT6OreLayerHelper.<init>(GT6OreLayerHelper.java:22) ~[GT6OreLayerHelper.class:?]
> 	at pers.gwyog.gtneioreplugin.GTNEIOrePlugin.onLoadComplete(GTNEIOrePlugin.java:38) ~[GTNEIOrePlugin.class:?]
>......
